services:
  airc:
    build:
      context: .
      dockerfile: Dockerfile
      target: airc
    image: airc
    restart: "no"
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./cache:/root/.cache
      - ./src:/opt/airc/src:rw
    cap_add: # used for running ze-monitor within airc container
      - CAP_DAC_READ_SEARCH # Bypass all filesystem read access checks
      - CAP_PERFMON         # Access to perf_events (vs. overloaded CAP_SYS_ADMIN)
      - CAP_SYS_PTRACE      # PTRACE_MODE_READ_REALCREDS ptrace access mode check

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter
    image: jupyter
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    ports:
    - 8888:8888 # Jupyter Notebook
    volumes:
      - ./jupyter:/opt/jupyter:rw
      - ./cache:/root/.cache
